drop table scan;
drop table folder;
drop table scan_owner;
drop table scan_type;
drop table timezone;
create table folder (id           int          not null, name         varchar(255) null, type         varchar(255) null, default_tag  int          null, custom       int          null, unread_count int          null, constraint folder_pk primary key (id) );
alter table folder disable keys;
create table scan_owner (id    int auto_increment, owner varchar(255) not null, constraint scan_owner_pk primary key (id) );
create unique index scan_owner_owner_uindex on scan_owner (owner);
create table scan_type ( id   int auto_increment, type varchar(255) not null, constraint scan_type_pk primary key (id) );
create unique index scan_type_type_uindex on scan_type (type);
create table timezone (id       int auto_increment, timezone varchar(255) not null, constraint timezone_pk primary key (id) );
create unique index timezone_timezone_uindex on timezone (timezone);
create table scan ( id              int          not null, name            varchar(255) null, uuid            varchar(255) null, folder_id       int          null, owner_id        int          null, type_id         int          null, rrules          varchar(255) null, `read`          boolean      null, shared          boolean      null, enabled         boolean      null, control         boolean      null, user_permissions int         null, status          varchar(255) null, creation_date   timestamp    null, start_time      varchar(255) null, last_modification_date  timestamp null, timezone_id     int          null, live_results    int          null, constraint table_name_pk primary key (id), constraint table_name_folder_id_fk foreign key (folder_id) references folder (id), constraint table_name_scan_owner_id_fk foreign key (owner_id) references scan_owner (id), constraint table_name_scan_type_id_fk foreign key (type_id) references scan_type (id), constraint table_name_timezone_id_fk foreign key (timezone_id) references timezone (id) );
alter table scan disable keys;